USER = 'asterisk' #ARI username
PASS = 'asterisk' #ARI password
APP = 'hello-world' #ARI Application name similar to Stasis dialplan application name
BOT_URL = 'ws://127.0.0.1:8080'
RTP_SERVER = '0.0.0.0'
RTP_PORT = 6000
CODEC = 'ulaw'
REDIS_HOST = 'localhost'
REDIS_PORT = 6379