USER = 'asterisk' #ARI username
PASS = 'asterisk' #ARI password
APP = 'voicebot-app' #ARI Application name similar to Stasis dialplan application name
BOT_URL = 'ws://127.0.0.1:8080' #Bot url to connect and send streaming events on it
RTP_SERVER = '0.0.0.0' #Listening media stream on this server
RTP_PORT = 6000 #Port of media server
ASTERISK_SERVER = 'localhost'
ASTERISK_PORT = '8088'
EXTERNAL_APP_SERVER = '127.0.0.1' # 13.233.208.0 this is IP of server where your code is placed
CODEC = 'ulaw' #codec for streaming
REDIS_HOST = 'localhost' #Redis server
REDIS_PORT = 6379 #Redis port
EN_FILLER_ARRAY = ["okay_fine_new","checking_that_for_new"]
HI_FILLER_ARRAY = ["wait_a_moment_hindi_new", "give_me_moment_hindi_new"]
GU_FILLER_ARRAY = ["give_me_sec_gujarati_new","give_me_some_time_gujarati_new"]